# Generated by Django 3.2 on 2023-01-31 17:53

import api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[api.v1.validators.UnicodeUsernameValidator(), api.v1.validators.username]),
        ),
    ]
